name: dd2421
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.8.0=pyhd8ed1ab_0
  - arrow=1.3
  - async-lru=2.0.4=py310hca03da5_0
  - attrs=24.3.0=py310hca03da5_0
  - babel=2.16.0=py310hca03da5_0
  - beautifulsoup4=4.12.3=py310hca03da5_0
  - blas=1.0=openblas
  - brotli-python=1.0.9=py310h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - certifi=2025.4.26=py310hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.12=py310h853098b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h313beb8_0
  - fonttools=4.55.3=py310h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=h13f89a0_1
  - glib=2.69.1=h514c7bf_2
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - icu=68.1=hc377ac9_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.5=py310hca03da5_0
  - joblib=1.4.2=py310hca03da5_0
  - jpeg=9e=h80987f9_3
  - json5=0.10.0=pyhd8ed1ab_1
  - jupyter_client=8.6.3=py310hca03da5_0
  - jupyter_core=5.7.2=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_0
  - jupyter_server=2.15.0=py310hca03da5_0
  - jupyter_server_terminals=0.5.3=py310hca03da5_0
  - jupyterlab=4.3.4=py310hca03da5_0
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.27.3=py310hca03da5_0
  - krb5=1.20.1=h69eda48_0
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=19.1.7=ha82da77_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libllvm12=12.0.0=h12f7ac0_4
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.20=h02f6b3c_0
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.46.0=hfb93653_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.10.4=h372ba2a_0
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=19.1.7=hdb05f8b_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=2.2.0=py310hca03da5_1
  - matplotlib=3.10.0=py310hca03da5_0
  - matplotlib-base=3.10.0=py310h7ef442a_0
  - mistune=3.1.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - notebook=7.3.2=py310hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.4.0=h81ee809_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pcre=8.45=hc377ac9_0
  - pcre2=10.42=hb066dcc_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.0.0=py310h84e58ab_1
  - pip=24.2=py310hca03da5_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py310h078409c_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyparsing=3.2.0=py310hca03da5_0
  - python=3.10.13=h2469fbe_1_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-json-logger=2.0.7=py310hca03da5_0
  - python_abi=3.10=7_cp310
  - pytz=2024.1=py310hca03da5_0
  - pyzmq=26.2.0=py310h313beb8_0
  - qt-main=5.15.2=ha2d02b5_7
  - readline=8.2=h1a28f6b_0
  - referencing=0.36.1=pyhd8ed1ab_0
  - rpds-py=0.22.3=py310h2aea54e_0
  - scikit-learn=1.7.0=py310h48c93d9_0
  - scipy=1.15.2=py310h14fe6a6_1
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=72.1.0=py310hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tk=8.6.14=h6ba3021_0
  - typing_extensions=4.12.2=py310hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310h80987f9_1
  - wheel=0.44.0=py310hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hfb09047_0
  - pip:
      - absl-py==2.2.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - bleach==6.2.0
      - cachetools==5.5.2
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - cheroot==10.0.1
      - comm==0.2.2
      - contourpy==1.3.1
      - cryptography==44.0.2
      - defusedxml==0.7.1
      - etils==1.12.2
      - exceptiongroup==1.2.2
      - fastjsonschema==2.21.1
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gast==0.6.0
      - gcsfs==2025.5.1
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.1
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - graphviz==0.20.3
      - grpcio==1.71.0
      - gviz-api==1.10.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jaraco-functools==4.1.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-lsp==2.2.5
      - jupyterlab-widgets==3.0.13
      - keras==3.10.0
      - keras-flops==0.1.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.5.0
      - namex==0.0.8
      - nbclient==0.10.2
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nnfs==0.5.1
      - notebook-shim==0.2.4
      - numpy==2.1.3
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pdfminer-six==20231228
      - pdfplumber==0.11.5
      - pexpect==4.9.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydot==4.0.0
      - pygments==2.19.1
      - pypdfium2==4.30.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rsa==4.9.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-profile==2.20.1
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xprof==2.20.1
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /Users/yanjun/Documents/apps/miniconda3/envs/dd2421
